### ISSUE TITLE
Unable to open dataframe to view in data viewer

### ISSUE THREAD

**Issue by vincenttang0912** [microsoft/vscode-data-wrangler#176] opened 2024-05-13 22:05 UTC
## Environment data

-   VS Code version: 1.83.1
-   Data Wrangler Extension version (available under the Extensions sidebar): 1.0.2
-   Jupyter Extension version (available under the Extensions sidebar): 2023.10.1100000000
-   Python Extension version (available under the Extensions sidebar): 2024.2.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11 Enterprise OS build 22631.3447
-   Pandas version: 2.1.1
-   Python and/or Anaconda version: Python 3.12.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA

## Expected behaviour

Show dataframe when clicking on "Show variable snapshot in data viewer" button in the Variables View.

## Actual behaviour

Error Message:
Did not receive notebook URI from Jupyter extension. This likely means that the Data Wrangler extension is not compatible with the Jupyter extension. Please file an issue on the Data Wrangler GitHub repository.

## Steps to reproduce:

#%%
import pandas as pd
df = pd.DataFrame({'A':['a','aa','aaa'], 'B':['b','bb','bbb']})

# 1) Click on Variables in the interactive window
# 2) Click on the "Show variable snapshot in data viewer" button which is on the left of the variable 'df'

![image](https://github.com/microsoft/vscode-data-wrangler/assets/46409167/fc57000e-8832-4d18-b39d-125b97ec8ff1)
![image](https://github.com/microsoft/vscode-data-wrangler/assets/46409167/0890202e-bcbe-4635-a780-d61581adc809)

**Comment by kycutler** [comment] 2024-05-16 15:58
Hi @vincenttang0912, thanks for opening this issue and for trying Data Wrangler!

Are you able to upgrade your VS Code version?

The issue is due to the older version of the Jupyter extension (from October of last year). Unfortunately, there is nothing we can do from the Data Wrangler side to address this, since this version of the Jupyter extension doesn't send some necessary data from the Variables panel. Additionally, newer releases of the Jupyter extension only support more recent versions of VS Code. If you can upgrade VS Code, you should be able to install a version of Jupyter that works:
- VS Code `1.87.0` + Jupyter `v2024.2.0` should allow you to open the old data viewer
- VS Code `1.88.0` + Jupyter `v2024.3.0` should allow you to open Data Wrangler

Hope this helps!

**Comment by vincenttang0912** [comment] 2024-05-21 20:57
This worked, thank you!

**Comment by pwang347** [comment] 2024-05-21 23:44
Closing the issue as it has been resolved. Thanks!

**Closed by pwang347** 2024-05-21 23:44 UTC
