### ISSUE TITLE
DW (often) fails to open DataFrame from other frames on the call stack

### ISSUE THREAD

**Issue by danhje** [microsoft/vscode-data-wrangler#279] opened 2024-09-09 07:43 UTC
## Environment data

-   VS Code version: 1.92.2
-   Data Wrangler Extension version (available under the Extensions sidebar): v1.8.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.7.0
-   Python Extension version (available under the Extensions sidebar): v2024.14.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11 with Ubuntu on WSL2
-   Pandas version: 2.2.2
-   Python and/or Anaconda version: 3.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry venv

## Expected behaviour

DataFrame opens in DW.

## Actual behaviour

Nothing happens.

## Steps to reproduce:

Put a breakpoint on the first `return` line of the following script, and run it in VS Code debugger.

```python
import pandas as pd


def inner():
    inner_var = pd.DataFrame()
    return

def outer():
    outer_var = pd.DataFrame()
    inner()

outer()
```

The (empty) DF `inner_var` can be opened in DW. Now find the "CALL STACK" panel and click "outer". The "VARIABLES" panel now previews `outer_var`. But opening it in DW often fails, though not always.

This could be a VS Code issue and not a DW issues, but since `outer_var` clearly is available (you can inspect it and modify it in the debug console) my first guess would be DW.

**Comment by pwang347** [comment] 2024-09-09 18:30
Hi @danhje, thanks for the issue report! I can confirm that it reproduces for me as well. However, it looks like the DW command is never invoked in this case, so it seems like there's an issue somewhere in the variable data delegation. I'll transfer this issue to the Jupyter folks.

**Comment by pwang347** [comment] 2024-09-09 18:32
Will close this for now, but we can reopen it if it turns out there's something we can do on our side as well!

**Closed by pwang347** 2024-09-09 18:32 UTC
Labels: external
