### ISSUE TITLE
Improvements to Data Wrangler tab naming

### ISSUE THREAD

**Issue by AmrSol** [microsoft/vscode-data-wrangler#229] opened 2024-07-11 14:40 UTC
Data wrangler's tabs are very long and they make the UX unbearable. For example when opening a dataframe found within a class, i.e. data.df, the tab name is:
"Debug filename.py (data.df) - Data Wrangler"

<img width="433" alt="Screenshot 2024-07-11 at 16 39 57" src="https://github.com/microsoft/vscode-data-wrangler/assets/75169160/6f13b574-3056-47f9-941f-e2b452a5e7c5">

Why?? "data.df" with the Data Wrangler icon/logo is more than enough. Please fix this. Im sure its a quick fix. I mainly view dataframes when debugging python files all the time.

## Environment data

Version: 1.91.0 (Universal)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:54:18.541Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

**Comment by pwang347** [comment] 2024-07-11 17:37
Hi @AmrSol, thanks for opening the issue! We just recently merged an update to address this in our pre-release version (v1.5.2+). Please give this a try and let me know if you have any additional feedback.

I will close this for now as a dupe of https://github.com/microsoft/vscode-data-wrangler/issues/205, but do feel free to re-open this if you have any additional comments!

**Comment by AmrSol** [comment] 2024-07-12 11:25
Hi @pwang347, thank you for your speedy reply. I still think it is cluttered unfortunately. For those that work on 14 or 16 inch laptop screens, the tab name format does not allow for easy identification of the variable name. 

<img width="1512" alt="Screenshot 2024-07-12 at 13 16 28" src="https://github.com/user-attachments/assets/217b1514-d5ac-4d8e-898f-bda9f1d6e670">

For example, an option where the tabs could just display the variable name would be perfect. It could be an option in the settings. Something like this:

{colourful DW icon} {variable name}

Also the extension Rename Tabs by luke-callaghan doesn't work with the pre-release tabs.

**Comment by pwang347** [comment] 2024-07-12 19:43
@AmrSol Got it, thank you for the feedback! We will re-open this issue and see if anyone else can chime in for more comments before we implement further changes.

Note that we currently need to include the `[DW]` part mostly due to not having the following feature available, so a suffix is needed as a workaround for the icon otherwise: [Add ability to apply custom icon to Custom Editors · Issue #105028 · microsoft/vscode (github.com)](https://github.com/microsoft/vscode/issues/105028)

Regarding the extension - the data viewer window from debugger entry is not currently tied to an actual file on disk, so I suspect that that's what is causing the rename extension to fail.

Hope the above helps!

**Comment by war-live** [comment] 2024-07-16 11:40
Hi 

Thanks for raising the long name, I was also going to.
I have a 34" screen and the names are too long for me, especially if you split the display 2/3, 1/3.
using the 'Open editors' window help a little, but even then the variable name is hidden off to the right, if the pane is too small

The old built in data viewer used only the variable name and this worked fine for me.
I can see how having the file name could be useful, but in reality a shorter tab with just the variable name is the least aggravating. 
Otherwise make the tab name configuration a user option.
but also put the variable name first, then a wide open editors pane is not needed and it is easer to spot what variable you are looking at - having the variable name in the middle takes longer to find/realise if you are looking at the correct thing.

**Comment by pwang347** [comment] 2024-07-17 21:00
Hi @AmrSol, @war-live - what do you think about something like this?

1. Only variable name is shown by default, but can hover over file path to see the original file
<img width="264" alt="image" src="https://github.com/user-attachments/assets/6d63a7eb-4fc0-467e-be26-f3b75e1a99b7">

2. For repeated launches on same variable, show counter next to variable name
<img width="248" alt="image" src="https://github.com/user-attachments/assets/37a2cf4a-e31f-48ff-9820-2990b61d8212">

3. If multiple notebooks have the same variable name, let VS Code disambiguate using secondary heading (trick is to use original file as a folder name)
<img width="384" alt="image" src="https://github.com/user-attachments/assets/30e12c2d-4bbf-409e-a26a-33a332d6b660">

Note that in some scenarios (e.g. Python debuggers) we don't have access to the original source file path, so we wouldn't be able to show anything uniquely identifying for the hover/disambiguation part there.

**Comment by AmrSol** [comment] 2024-07-17 21:53
Hey @pwang347, this looks great for me. Would be very interesting to test. 😄 What do you thinnk @war-live ?
With regards to Python debuggers (which is what I mainly use (and most of my colleagues use as well)) it is completely fine to not show anything to uniquely identify the variables as we are used to this from VSCode's  data viewer. Would it still show the file names next to it in that case?

**Comment by pwang347** [comment] 2024-07-17 23:40
@AmrSol Great to hear! Since the tab names are no longer always unique, I think VS Code will by default try to show the path in the secondary text if there is a collision. For Python debuggers, current thinking is to try getting a path if it exists and if not to just fallback to the debugger name:
<img width="326" alt="image" src="https://github.com/user-attachments/assets/455c1a13-fc33-4fa0-aef6-1668f77bc2ed">

Unfortunately, it seems like it's not possible to get rid of the `/` prefix (or `\` for windows) as simply having a name string is interpreted as a file path from root and in general there isn't a relative path to use.

**Comment by war-live** [comment] 2024-07-18 07:13
Hi @AmrSol , @pwang347. It looks like we are on different time zones.
@pwang347, as to your suggestions. I am happy with them, I think they will greatly aid easy-of-use.
It looks like you have a proposal that is ready for field testing, before over optimising (I am often guilty of that).
Thanks for all the effort; 90% of the work is polishing the details...

**Comment by pwang347** [comment] 2024-07-24 22:12
Hi @AmrSol, @war-live, just a heads up that the change is now live in the latest pre-release v1.5.4!
Thank you again for your patience as well as valuable contributions to this discussion. Please give it a try and let me know what you think!

**Closed by pwang347** 2024-07-24 22:12 UTC
Labels: enhancement

**Comment by war-live** [comment] 2024-07-25 07:55
Hi

Tested, and it works well.
It will definitely make my navigation easier.

Thanks
Warren

+44 (0)77 8707 1392
________________________________
