### ISSUE TITLE
feature request: add option to disable opening sidebar+console

### ISSUE THREAD

**Issue by bobcolner** [microsoft/vscode-data-wrangler#96] opened 2023-10-14 18:32 UTC
The current behavior of data-wranggler provides a poor UX on smaller screens. Please give an option to disable opening the side-bar and console view. Thanks!

**Comment by pwang347** [comment] 2023-10-18 22:49
Hi @bobcolner, thanks for making this feature request! This is a great callout - we're currently exploring different ways to address the panel real estate issue and will provide any updates here.

**Comment by kleinlennart** [comment] 2024-05-24 09:48
I would really appreciate this as well, since I find it incredibly annoying to have to close it again and again every time I just want to have a look at my data and don't need to see the basic Data Summary.

**Comment by PiStar** [comment] 2024-07-30 08:50
Please add this, many thanks.

**Comment by yanyu2015** [comment] 2024-08-13 06:51
This is a great callout, please!

**Comment by jonpedros** [comment] 2024-09-27 05:49
I just think an option should be added to not open the panel. I don't think it's a matter of re-thinking the side bar philosophy.

**Comment by guidocioni** [comment] 2024-10-29 10:22
I was about to open an issue on this, then I realized it was already done. Please change this standard behaviour: it does not happen for other extensions!

**Comment by tacitli** [comment] 2024-10-31 17:47
Please add this, has been a pain for a while. Much appreciated!

**Comment by BrazilForever11** [comment] 2024-11-12 19:51
It would be great to be able to change Data Summary panel behavior in Settings similar to enabling/disabling Column Insight.

**Comment by pwang347** [comment] 2024-11-20 00:42
Hi folks! Thank you very much for your patience and for providing great feedback on this issue.

We've just added a setting to disable the automatic panel behaviour in pre-release version 1.13.3. The following setting needs to be disabled to prevent the panels from appearing on startup and on tab focus:
![Image](https://github.com/user-attachments/assets/46662079-2493-471c-8b90-cfbdff49e532)

Please feel free to give this a try and let us know if you have any additional feedback. Thanks!

**Closed by pwang347** 2024-11-20 00:42 UTC
Labels: feature

**Comment by guidocioni** [comment] 2024-11-20 10:47
> Hi folks! Thank you very much for your patience and for providing great feedback on this issue.
> 
> We've just added a setting to disable the automatic panel behaviour in pre-release version 1.13.3. The following setting needs to be disabled to prevent the panels from appearing on startup and on tab focus: ![Image](https://github.com/user-attachments/assets/46662079-2493-471c-8b90-cfbdff49e532)
> 
> Please feel free to give this a try and let us know if you have any additional feedback. Thanks!

Finally! :) Thanks a lot. I can confirm it is indeed working on the pre-release version
