### ISSUE TITLE
Feature Request: Auto re-size column width

### ISSUE THREAD

**Issue by bradenpecora** [microsoft/vscode-data-wrangler#245] opened 2024-08-01 21:30 UTC
I do a lot of work with matrices for physics simulations, and Data Wrangler's integration with VSCode's debugger is extremely useful for investigating these matrices. However, columns are very large in Data Wrangler, so it is hard to see all the data/time consuming to resize every column. I would appreciate the ability to specify the default column width or an option always automatically resize all columns to the width of the data.

Thanks for your consideration!

**Comment by pwang347** [comment] 2024-08-02 20:48
Hi @bradenpecora, thank you for opening the request! Closing as a dupe of https://github.com/microsoft/vscode-data-wrangler/issues/206 as it seems to be similar. Please feel free to follow that thread for updates!

**Closed by pwang347** 2024-08-02 20:48 UTC
