### ISSUE TITLE
Data Wrangler view does not remember hidden side bar / bottom panel

### ISSUE THREAD

**Issue by tea-de-kay** [microsoft/vscode-data-wrangler#103] opened 2023-11-16 12:51 UTC
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

When I hide the side bar and the panel in the Data Wrangler view, change the tab to an open notebook and return to the Data Wrangler view, the side bar and the panel show up again. I expect, them to stay hidden upon tab switch.

# Diagnostic data

-   Jupyter extension version: 2023.10.1100000000
-   Python extension version: 2023.20.0
-   .NET Install Tool for Extension Authors extension version: 2.0.0
-   Python package dependencies:

```json
{
  "satisfied": {
    "pandas": {
      "installedVersion": "2.1.3",
      "requiredVersion": "0.25.2"
    }
  },
  "unsatisfied": {}
}
```

Extension version: 0.20.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.9-1-MANJARO
Modes:

**Comment by pwang347** [comment] 2023-11-29 02:30
Hi @tea-de-kay, thanks for opening this issue!

Note that this behaviour is currently by design due to limitations with VS Code API. However, we are experimenting with  some fixes to improve this experience. I will update this thread when the changes are checked in.

**Comment by ryanyord** [comment] 2024-02-04 20:48
Wanted to add my support for this request.  Often I will be switching between the data wrangler view & my jupyter notebook and it is frustrating to have to close the bottom and side panel. Awesome extension though, thanks for the extension!

**Comment by hashtagswagboy** [comment] 2024-03-20 22:16
Adding support as well. Definitely wish there were a way to have the panel and side bar auto close when exiting the data wrangler editor.

**Comment by pszewi** [comment] 2024-07-14 20:10
Adding support for this as well. This would be a great addition!

**Comment by xj-liu** [comment] 2024-09-20 17:02
Adding my support. Definitely in need of this feature.

**Comment by cstork** [comment] 2024-11-09 11:07
One more in support of this feature/bugfix!

**Comment by pwang347** [comment] 2024-11-20 00:57
Hi folks! Just wanted to let you know that there is now an option to not automatically reveal the panels (both on startup and on tab switch) in pre-release version 1.13.3.

For more details, please see: https://github.com/microsoft/vscode-data-wrangler/issues/96#issuecomment-2487056292

Will close this issue for now since this setting should address the pain points mentioned here, but please feel free to reopen if you have additional feedback. Thanks!

**Closed by pwang347** 2024-11-20 00:57 UTC
Labels: enhancement
