### ISSUE TITLE
Copy columns directly and hide column insights by default

### ISSUE THREAD

**Issue by iBubb1e** [microsoft/vscode-data-wrangler#244] opened 2024-08-01 13:26 UTC
## Environment data

-   VS Code version: XXX
-   Data Wrangler Extension version (available under the Extensions sidebar): 1.6.0
-   Jupyter Extension version (available under the Extensions sidebar): 2024.6.0
-   Python Extension version (available under the Extensions sidebar): 2024.12.1
-   OS (Windows | Mac | Linux distro) and version: Win11
-   Pandas version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Expected behaviour

1. Copy columns directly
2. hide column insights by default

## Actual behaviour

Both can't be realized currently.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by pwang347** [comment] 2024-08-01 18:16
Hi @iBubb1e, thanks for opening this request! It seems like this may be duplicate of the following issues:
- Copy columns directly: https://github.com/microsoft/vscode-data-wrangler/issues/179
- Hide column insights by default: https://github.com/microsoft/vscode-data-wrangler/issues/221

Will close the issue for now as duplicate, but please feel free to reopen if these are different from what you are looking for. Thanks!

**Closed by pwang347** 2024-08-01 18:16 UTC
