### ISSUE TITLE
Unable to view DataFrame in VS Code using Data Wrangler extension

### ISSUE THREAD

**Issue by mekanavsharma** [microsoft/vscode-data-wrangler#270] opened 2024-08-28 15:47 UTC
## Environment data

-   VS Code version: 1.92.2 (user Setup)
-   Data Wrangler Extension version (available under the Extensions sidebar): 1.6.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.7.0
-   Python Extension version (available under the Extensions sidebar): 3.12.3
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Pandas version: 2.2.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA

## Expected behaviour

Showed be able to view dataframe in new pop-up

## Actual behaviour

When attempting to view a DataFrame in Visual Studio Code using the Data Wrangler extension, I encounter the following error:
"Could not retrieve variable autos from the Jupyter extension. Please file an issue on the Data Wrangler GitHub repository."

## Steps to reproduce:

I've verified that the DataFrame exists and is accessible in my code.
The issue persists after restarting VS Code and updating all relevant extensions.
I can view the DataFrame using alternative methods (e.g., print statements, Jupyter notebooks), but not through the Data Wrangler extension.
![image](https://github.com/user-attachments/assets/4df59525-c06e-4de4-abf9-fb066537dfde)

![image](https://github.com/user-attachments/assets/de6d9145-0465-4b3d-a0e0-3ac34a078157)

These are the issues. 

Also, I am not able to see **Open 'df' in Data Wrangler** in my dataframe
![image](https://github.com/user-attachments/assets/a7cbd695-994a-47d1-83ad-030677a1b131)

**Comment by pwang347** [comment] 2024-08-28 18:44
Hi @mekanavsharma, thank you for opening this issue! Could you please confirm the following:
- Are you able to see the `Open 'df' in Data Wrangler` button and launch from the variable panel with the following simple DataFrame?
```python
df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
df
```

- Could you try to reproduce the issue again with the developer console open and check to see if there are any related error messages? You can open the developer console as follows:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/a609a131-2917-43f4-95a2-8c28db3ae5fe">
<img width="282" alt="image" src="https://github.com/user-attachments/assets/12059f41-f5cb-466f-a54d-ada1fbb95c3d">

It would be very helpful if you could provide the information above. Thanks!

**Comment by mekanavsharma** [comment] 2024-08-28 19:20
> Hi @mekanavsharma, thank you for opening this issue! Could you please confirm the following:
> 
> * Are you able to see the `Open 'df' in Data Wrangler` button and launch from the variable panel with the following simple DataFrame?
> 
> ```python
> df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
> df
> ```
> 
> * Could you try to reproduce the issue again with the developer console open and check to see if there are any related error messages? You can open the developer console as follows:
> 
> <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/8560030/362411912-a609a131-2917-43f4-95a2-8c28db3ae5fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzEwMDAsIm5iZiI6MTcyNDg3MDcwMCwicGF0aCI6Ii84NTYwMDMwLzM2MjQxMTkxMi1hNjA5YTEzMS0yOTE3LTQzZjQtOTVhMi04YzI4ZGIzYWU1ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTg0NTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWMwNzQzNDI0YWE2ZmQ1YWFlNGVlMTJiMmRjOGI4OWNjNDBjOTNiYTA2YjdhMTE1Nzc2OWQzNDVmNzhiOWUwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YLPr-4S18S2ckVYYMPYYnVY9Te26ZXaEs9U_gNvjzUw"> <img alt="image" width="282" src="https://private-user-images.githubusercontent.com/8560030/362412092-12059f41-f5cb-466f-a54d-ada1fbb95c3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzEwMDAsIm5iZiI6MTcyNDg3MDcwMCwicGF0aCI6Ii84NTYwMDMwLzM2MjQxMjA5Mi0xMjA1OWY0MS1mNWNiLTQ2NmYtYTU0ZC1hZGExZmJiOTVjM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTg0NTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU2NjZiZGM4MTNmMDYyMGUwOGMzMTQ4Y2E0NzdmM2NjOTNiMThmOTZkNGU0NTRiMmMwMGQ0NDNkMDJlNzY0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oCdR-24f6ZJ0DgRh-XBn72E1_MbPQFv49yBmXU1G0bE">
> It would be very helpful if you could provide the information above. Thanks!

Thanks for the help.

Point 1: 
No I am not able to see, _Open 'df' in Data Wrangler_

![image](https://github.com/user-attachments/assets/3f10d04e-7e8a-4325-b1da-8ff1d28e2cab)

Point 2:
Here is what I got when I reproduced the issue again with the developer console open.
![image](https://github.com/user-attachments/assets/5492b6d1-c62a-4136-ac08-c0f03e23c584)

On clicking "console.ts.137" I got:
![image](https://github.com/user-attachments/assets/6860c319-21e4-4a0d-a8a0-8608ac2d4a7b)

On Clicking "notificationsAlerts.ts.42" I got:
![image](https://github.com/user-attachments/assets/0c022914-da06-4f92-b458-2e9b3d4e22d5)

**Comment by pwang347** [comment] 2024-08-28 21:59
Hi @mekanavsharma, thanks for the quick response! Some more followups:
- Do you see a modal popup from Jupyter asking something like this? `Do you want to grant Kernel access to the extension Data Wrangler?`
- Do you by any chance have this setting enabled (and if so, could you try the steps in the link?) https://github.com/microsoft/vscode-data-wrangler/issues/129#issuecomment-1922177014
- If the above does not resolve the issue for you, I would recommend creating an issue on the [Jupyter extension](https://github.com/microsoft/vscode-jupyter) repository and attach Jupyter logs:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/0701e7e5-bf48-4e4b-a345-05e3daa696f0">
<img width="486" alt="image" src="https://github.com/user-attachments/assets/bd17ff2f-9c76-4a69-977a-ba92f95fc680">
(then reproduce the issue and copy output from the output panel)

**Comment by mekanavsharma** [comment] 2024-08-29 05:26
> Hi @mekanavsharma, thanks for the quick response! Some more followups:
> 
> * Do you see a modal popup from Jupyter asking something like this? `Do you want to grant Kernel access to the extension Data Wrangler?`
> * Do you by any chance have this setting enabled (and if so, could you try the steps in the link?) [Data Wrangler attempts to reinstall python and Jupyter ext when I already have them #129 (comment)](https://github.com/microsoft/vscode-data-wrangler/issues/129#issuecomment-1922177014)
> * If the above does not resolve the issue for you, I would recommend creating an issue on the [Jupyter extension](https://github.com/microsoft/vscode-jupyter) repository and attach Jupyter logs:
> 
> <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/8560030/355635287-0701e7e5-bf48-4e4b-a345-05e3daa696f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDkwMzUsIm5iZiI6MTcyNDkwODczNSwicGF0aCI6Ii84NTYwMDMwLzM1NTYzNTI4Ny0wNzAxZTdlNS1iZjQ4LTRlNGItYTM0NS0wNWUzZGFhNjk2ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDUxODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Y4ZWQ3M2E4ZDkwODRhMjkzNmZjZDdlYzU4M2U3OGM4ZjkyMmMwNzliYTJhZWNkMTFkOTk5YTdmNzEyOTAzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fpzrKwnWaSP2xc44gxj0aR4tFLGcl981lgUIvD9Mg0s"> <img alt="image" width="486" src="https://private-user-images.githubusercontent.com/8560030/355635935-bd17ff2f-9c76-4a69-977a-ba92f95fc680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDkwMzUsIm5iZiI6MTcyNDkwODczNSwicGF0aCI6Ii84NTYwMDMwLzM1NTYzNTkzNS1iZDE3ZmYyZi05Yzc2LTRhNjktOTc3YS1iYTkyZjk1ZmM2ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDUxODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRhMjYxYWJhZGU4YTY0OTQzMzU1Mzk5Mjg1MWM0OWMxNWMzN2YzNmQxNDI5ZTk0ZTczYzUwODBiM2VhZmFhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8s38NKQ4dA6dsWSBhg0FwPQpsI38GfyBzd2hSEpGz1U"> (then reproduce the issue and copy output from the output panel)

Thanks for the response :
1. No I didn't get any such popup.
2.  Here Is what I have in my settings :
![image](https://github.com/user-attachments/assets/46919001-6c78-4233-a03d-fa7800f9bf7f)

**Comment by pwang347** [comment] 2024-08-29 06:02
@mekanavsharma, got it thanks for giving it a try - actually your original settings is correct, the affinity setting is what has caused some problems previously.

This error message you posted below seems to be the culprit:
<img width="931" alt="image" src="https://github.com/user-attachments/assets/53e470b5-1193-4f0c-b713-9e9b2f3d1113">

Data Wrangler needs permission from the Jupyter extension to access the kernel and it seems to not have permission in this case, but it's strange that you're also not getting a popup. It would be great if you could open an issue on the Jupyter side, as this seems to be related to their kernel API.

**Comment by mekanavsharma** [comment] 2024-08-29 06:09
> @mekanavsharma, got it thanks for giving it a try - actually your original settings are correct, the affinity setting is what has caused some problems previously. Please remove that setting for now.
> 
> This error message you posted below seems to be the culprit: <img alt="image" width="931" src="https://private-user-images.githubusercontent.com/8560030/362550257-53e470b5-1193-4f0c-b713-9e9b2f3d1113.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTIwMzcsIm5iZiI6MTcyNDkxMTczNywicGF0aCI6Ii84NTYwMDMwLzM2MjU1MDI1Ny01M2U0NzBiNS0xMTkzLTRmMGMtYjcxMy05ZTliMmYzZDExMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDYwODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE0MGYwZGRhNWNjMWNiZGVmNjlhMmUzNzAyYWFlM2NhNTI0YWM5ZTVmYWE3MzA1YWViNWVmMDg3ODEzMWY0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-hd_0Da_mE2MqgzkhxQwpK8mwJ7hQMlVJMGAZoerIWw">
> 
> Data Wrangler needs permission from the Jupyter extension to access the kernel and it seems to not have permission in this case, but it's strange that you're also not getting a popup. It would be great if you could open an issue on the Jupyter side, as this seems to be related to their kernel API.

Thanks for the help.
Will do that.

**Comment by jjbochard** [comment] 2024-09-02 11:24
To solve this problem, I unchecked this settings 
![Capture d’écran 2024-09-02 à 13 23 34](https://github.com/user-attachments/assets/a2981c30-6d41-43b6-9c61-fe290890dcdd)

**Comment by mekanavsharma** [comment] 2024-09-03 06:38
> To solve this problem, I unchecked this settings ![Capture d’écran 2024-09-02 à 13 23 34](https://private-user-images.githubusercontent.com/44342342/363670907-a2981c30-6d41-43b6-9c61-fe290890dcdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDU1OTEsIm5iZiI6MTcyNTM0NTI5MSwicGF0aCI6Ii80NDM0MjM0Mi8zNjM2NzA5MDctYTI5ODFjMzAtNmQ0MS00M2I2LTljNjEtZmUyOTA4OTBkY2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA2MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZTdlYjlhYjI1YWU2YzU5ODMzYjExZTRjNTMyN2I3ZjY3ZDQ3YjA0YjYwMmQzYmZiYTQ2Yzc5MDE2MzhkMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1XkxUheo0U6o-1qnAiDlrzuZABEBbNQWngcsBDJmmKA)

It worked.
Thanks

**Comment by NiKoenig** [comment] 2024-09-03 07:02
> To solve this problem, I unchecked this settings ![Capture d’écran 2024-09-02 à 13 23 34](https://private-user-images.githubusercontent.com/44342342/363670907-a2981c30-6d41-43b6-9c61-fe290890dcdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDY3OTIsIm5iZiI6MTcyNTM0NjQ5MiwicGF0aCI6Ii80NDM0MjM0Mi8zNjM2NzA5MDctYTI5ODFjMzAtNmQ0MS00M2I2LTljNjEtZmUyOTA4OTBkY2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA2NTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMDY5YmFmMWFhNDZkZWQwZjNmZTZmMzUzODk4NzY5ZjZmNzdmMjVkOGRkMTQ1YTY3YWU3Yjg4NzI5ZjNlZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fxNsT_OfTS01Y-oV4CXpV_3grdaT7rY29Fnv03_t-WI)

Worked for me as well, thank you!! :)

**Comment by DonJayamanne** [comment] 2024-09-03 21:48
**Solution**
* Select the command `Jupyter: Manage Access to Jupyter kernels` from the command palette
* From the quick pick that appears, select the `Data Wrangler` extension

Also ensure the setting `Experiments: Use Jupyter Proposed API` is enabled.

The reason this may not have worked in the past is users may have received a prompt requesting `Data Wrangler` extension to gain access to Kernels. Its very likely this prompt was dismissed, meaning access was not granted.

The error message logged here is evidence of that
https://github.com/microsoft/vscode-data-wrangler/issues/270#issuecomment-2316779172

**Comment by pwang347** [comment] 2024-09-04 00:49
Thanks all!

Please follow the solution shared by @DonJayamanne as it will soon become the default option moving forward (and you may run into this issue again).
It seems like we can also handle this error better on our side to ask for permissions, so I will leave this issue open until that gets checked in.

**Comment by dark-tonebone** [comment] 2024-09-07 01:50
I have tried the the recommended steps and It's still not working.

I have a pandas dataframe, and i'm right-clicking, then selecting 'View Value in Data Viewer' and I get a small pop up error (attached).

My settings are exactly as described by Don Jayamanne ([here](https://github.com/microsoft/vscode-data-wrangler/issues/270#issuecomment-2327499782)).

![image](https://github.com/user-attachments/assets/c44bac45-8f0f-4733-bb55-8adbb38711d6)

**Comment by pwang347** [comment] 2024-09-07 01:58
Hi @dark-tonebone, could you please check to see if you have the same error message in the developer console?
<img width="610" alt="image" src="https://github.com/user-attachments/assets/04398ec8-b464-4885-a44e-f567df3b8094">

Do you also have this message or is it something different?
![image](https://github.com/user-attachments/assets/4b84ca44-0844-4e23-92fb-32a548f6ef67)

**Comment by DonJayamanne** [comment] 2024-09-08 07:53
Please can you share a screenshot of the following screen
Select the command Jupyter: Manage Access to Jupyter kernels from the command palette

**Comment by ZWX013** [comment] 2024-09-09 03:12
![微信截图_20240909111134](https://github.com/user-attachments/assets/fcd82053-1930-401a-b5cc-722f0720bd9d)
I also tried the the recommended steps and It's still not working.

**Comment by DonJayamanne** [comment] 2024-09-09 09:26
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by pwang347** [comment] 2024-09-09 21:18
@ZWX013 Could you please also expand the highlighted objects by clicking on the arrow?
![image](https://github.com/user-attachments/assets/66e40464-f8a5-4770-83bd-63a8f2763794)

After you expand it (and any other relevant errors above), it would be great if you could share the following log file
<img width="472" alt="image" src="https://github.com/user-attachments/assets/14e02710-54d8-42dd-890c-3680e9d6d320">
 
Thanks!

**Comment by dark-tonebone** [comment] 2024-09-09 22:55
Hi @DonJayamanne thanks for your response!

DataWrangler worked a bunch for me today, and then I encountered a dataframe it would not load. Here are the requested screenshots taken right after clicking 'View Value in DataViewer' (which failed to open my df in DataWrangler).

Expanded variable in my variable inspector
![image](https://github.com/user-attachments/assets/00b97c3a-999d-4cfc-afba-6a1438e50d79)

Jupyter Logs
![image](https://github.com/user-attachments/assets/a8147ded-bce7-433e-a96f-06095be6d570)

**Comment by dark-tonebone** [comment] 2024-09-09 22:56
@pwang347 sorry I'm not sure where in VSCode I can find that arrow to expand... It looks like you're in a web browser dev tools panel? I'm using VSCode on Windows 11.

**Comment by dark-tonebone** [comment] 2024-09-09 22:59
Interestingly, after closing and reopening VSCode, the DataWrangler now works with that exact same dataframe!

**Comment by pwang347** [comment] 2024-09-09 23:33
Hi @dark-tonebone! If you are able to view DataFrames sometimes, I think this is a different issue. The permissions issue would prevent you from viewing completely.

Could you please try the steps here? You should be able to also see the dev tools panel within VS Code:
https://github.com/microsoft/vscode-data-wrangler/issues/270#issuecomment-2334998717

Alternatively, you can try opening it this way:
<img width="376" alt="image" src="https://github.com/user-attachments/assets/e9c96acc-13d6-42b1-8af3-2fcb2f2fbb59">

**Comment by dark-tonebone** [comment] 2024-09-10 00:04
Hi @pwang347 thanks for the updated instructions to access the dev tools :) 

I managed to make it error again. It happened soon after i closed a DataWrangler window that was stale from an old debug session. I closed it while some code was running.

Anyways, here are the screenshots and files you requested in your previous comment:
1) Screenshot of 'Console' tab immediately after error
![image](https://github.com/user-attachments/assets/08e8de86-f643-4c30-8c2e-bdcc6cf1a5f6)

2) Screenshot of expanded error line
![image](https://github.com/user-attachments/assets/3abcce1e-9ddd-4f6b-8fb3-df8c26e5cdf8)

3) Screenshot of the notificationAlerts.ts file
![image](https://github.com/user-attachments/assets/fe916480-9b61-4bac-bf3b-0bc9d1eed549)

4) .log file obtained by right-clicking the error and saving as
[vscode-app-1725926313871.log](https://github.com/user-attachments/files/16937691/vscode-app-1725926313871.log)

**Comment by pwang347** [comment] 2024-09-10 00:27
Hi @dark-tonebone, no problem and thank you for sharing the logs! Looks like you're running into this issue https://github.com/microsoft/vscode-data-wrangler/issues/275

We should have a fix soon this week, but if you'd like a workaround build for now it's available here: https://github.com/microsoft/vscode-data-wrangler/issues/275#issuecomment-2336852687

**Comment by dark-tonebone** [comment] 2024-09-10 00:36
Awesome! Great to hear there's a fix incoming. I'm happy to wait for the update. Thanks for your prompt responses on this issue, it's very much appreciated 💯

**Comment by pwang347** [comment] 2024-09-10 17:55
@dark-tonebone small update, the fix should be available now in pre-release 1.9.2. Please feel free to give it a try and let me know if you're still running into any issues!

**Comment by WulfNovak** [comment] 2024-09-10 20:18
@pwang347 

Hello,

Have been following this thread and trying the suggestions. I have unable to view the data viewer regardless of suggestion. After the recent pre-release this still holds true. Give same information as dark-tonebone as best I can.

Here are my existing settings relevant to this thread: 
1. Selected Experimental:
![image](https://github.com/user-attachments/assets/c4cf4abf-287d-4094-b6e4-23a94f5dad93)
2. Installed Data Wrangler v1.9.2 (pre-release)

Console tab has a lot of information - here is the screenshot of the bottom portion
![image](https://github.com/user-attachments/assets/afb89480-7e9d-430e-870f-76adcb1648d7)

Screenshot of the notificationsAlerts
![image](https://github.com/user-attachments/assets/74682137-f0ad-456c-9e91-9c8b34a23a39)
![image](https://github.com/user-attachments/assets/5d207d0c-c528-4dcb-ae60-6f3f78d4a478)

.log file
[vscode-app-1725999265621.log](https://github.com/user-attachments/files/16950408/vscode-app-1725999265621.log)

**Comment by pwang347** [comment] 2024-10-30 00:05
Closing this issue now as there are no new related issues. We've also added a notification in pre-release 1.13.1 to properly detect permission errors and to bubble them up appropriately. Thanks all!

**Closed by pwang347** 2024-10-30 00:05 UTC
Labels: documentation
