### ISSUE TITLE
Data explorer fails to load data with `name 'undefined' is not defined`

### ISSUE THREAD

**Issue by smaggis** [microsoft/vscode-data-wrangler#146] opened 2024-03-06 13:45 UTC
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual
Expected: 
- df = pd.load_csv('some_file_without_first_col_name.csv'), index_col=0)
- Go to side tab > Jupyter: Variables > Click Data Explorer icon on the left of the dataFrame
- Data Wrangler window

Actual:
Failed to load data
[A crashed paper plane.]
Error details
name 'undefined' is not defined

(But accessing from the notebook cell still works)

## Steps to reproduce:
df = pd.load_csv('some_file_without_first_col_name.csv'), index_col=0)
Go to side tab > Jupyter: Variables > Click Data Explorer icon on the left of the dataFrame

# Diagnostic data

-   Jupyter extension version: 2023.11.1100101639
-   Python extension version: 2024.2.1
-   .NET Install Tool for Extension Authors extension version: 2.0.2
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.1.4"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

Extension version: 0.28.0
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin x64 22.6.0
Modes:
Remote OS version: Linux x64 5.15.0-94-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|15, 10, 7|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id aca254ee-7f89-4df8-8077-d593b5bbeb9f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime|
|OS|Linux x64 5.15.0-94-generic|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|Memory (System)|31.07GB (8.65GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
bg6jg535:30979843
ccp1r3:30958155
dsvsc020:30976470

```

</details>

**Comment by kycutler** [comment] 2024-03-18 23:41
Hi @smaggis, thanks for opening this issue! I'm having trouble reproducing it however -- would you be able to share a sample notebook / dataset that triggers the issue?

**Comment by Jonecy-wzc** [comment] 2024-03-24 08:09
I also met this problem. when I click "view variable", the jupyter kernel will then crash.

**Comment by Jonecy-wzc** [comment] 2024-03-24 08:14
But it works well when I first run the df.head() in a jupyter cell and then click "Open df" below this cell. What's the problem?

**Comment by pwang347** [comment] 2024-04-19 18:16
@Jonecy-wzc thanks for the comment, could you let me know what version of Data Wrangler you were using? Could you try the latest pre-release version (0.29.8) to see if the issue still happens there?

**Comment by pwang347** [comment] 2024-04-19 23:58
It seems like this issue is due to having an old Jupyter extension version (e.g. `2023.11.1100101639`). It is resolved by updating to either latest stable or pre-release. Closing for now, but feel free to re-open if needed!

**Closed by pwang347** 2024-04-19 23:58 UTC
Labels: bug, info needed
