### ISSUE TITLE
Could not retrieve variable df1 from the Jupyter extension. Please file an issue on the Data Wrangler GitHub repository.

### ISSUE THREAD

**Issue by IwonaZwierzynska** [microsoft/vscode-data-wrangler#265] opened 2024-08-23 09:31 UTC
## Environment data

-   VS Code version: 1.92.2
-   Data Wrangler Extension version (available under the Extensions sidebar): v1.7.2 (pre-release)
-   Jupyter Extension version (available under the Extensions sidebar): v2024.8.2024080201 (pre-release)
-   Python Extension version (available under the Extensions sidebar): v2024.12.3
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise
-   Pandas version: -
-   Python and/or Anaconda version: Python 3.11 (64 bits)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

Displaying PySpark DataFrame in a form of table

## Actual behaviour

Error: Could not retrieve variable df1 from the Jupyter extension. Please file an issue on the Data Wrangler GitHub repository. by test debugging

The same error occurs, when I would like to open DataFrame from Jupyter Notebook (from variables section) 

## Steps to reproduce:

Trying to open "View Value in Data Viewer" with context menu on df1 (PySpark DataFrame) while debugging tests with pytest

![image](https://github.com/user-attachments/assets/d4ef178d-eb20-4de0-b36b-1d23cda0c53e)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

## Details

> •	How frequently is the issue happening for you? Is it all the time or only in some scenarios?

Always

> •	The type of data you are launching (e.g. large Pandas DataFrame with strings and numbers, etc.)

PySpark DataFrame with strings and numbers

> •	Are you running into the same issue even if it is something simple like the following?

I am not able to open only DataFrames from PySpark, lists (as an example) work correctly

> •	Any errors or abnormal messages in the developer console logs that seem related?

![image](https://github.com/user-attachments/assets/1eab4987-dff5-47bf-ace2-1f92d5d90f45)

> •	Do you have multiple Python environments? If so, could you please check if the issue is occurring in other environments as well? You can change it by clicking the environment selector in the bottom right:
> [image.png (view on web)](https://urldefense.com/v3/__https:/github.com/user-attachments/assets/01ee2ef8-1cbc-4fc6-84bb-40bb03cff4df__;!!MjrZg_cyo6Q!Jl9Yi2EZqOBL3gzEPnOH_UY_GBlLjP3oDQTDNofDCnfEOJLmuCEPUpjfhDsqsOPYWcMxeaVv6uJSVExuTDVrdzs-gIv6nyJnEw$) 

No.

> •	Lastly, are you using the [interactive window](https://urldefense.com/v3/__https:/code.visualstudio.com/docs/python/jupyter-support-py__;!!MjrZg_cyo6Q!Jl9Yi2EZqOBL3gzEPnOH_UY_GBlLjP3oDQTDNofDCnfEOJLmuCEPUpjfhDsqsOPYWcMxeaVv6uJSVExuTDVrdzs-gIuM4mU-JQ$) debugger or the default debugpy? ie. what button or command do you press to start debugging?

It does not matter, if it is in an interactive Window, JupyterNotebook or directly in VS I am not able to display DataFrames.

Thank you very much for your help in advance.

Best regards,
Iwona

**Comment by pwang347** [comment] 2024-08-23 20:57
Hi @IwonaZwierzynska, thank you for providing the extra details here! Seems like this is actually a duplicate of https://github.com/microsoft/vscode-data-wrangler/issues/255.

For some more context, we don't currently support loading PySpark variables but the Jupyter launch button shows it as something that can be launched because the type name happens also to be "DataFrame". We plan to both make the error message more clear as well as investigate the feasibility of PySpark support here.

For now, my recommendation is to convert the Spark DataFrame to Pandas using `pdf1 = df1.toPandas()` and view it that way. Hope this helps!

**Closed by pwang347** 2024-08-23 20:57 UTC

**Comment by NiKoenig** [comment] 2024-08-27 07:53
Hi @pwang347,

I get the exact same error message as @IwonaZwierzynska. In my case, it does not seem to be caused by PySpark not being supported, since my dataframe already is a pandas dataframe. I get the error message in the Interactive Mode.

**Comment by pwang347** [comment] 2024-08-28 18:47
Hi @NiKoenig, thank you for letting me know.

Could you please try to reproduce the issue again with the developer console open and check to see if there are any related error messages?

You can open the developer console as follows:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/a609a131-2917-43f4-95a2-8c28db3ae5fe">
<img width="282" alt="image" src="https://github.com/user-attachments/assets/12059f41-f5cb-466f-a54d-ada1fbb95c3d">

Thanks!

**Comment by NiKoenig** [comment] 2024-08-29 09:36
Hi @pwang347 

I get 4 error messages in the Toggle Developer Console (the first two are very long, sorry): 
![grafik](https://github.com/user-attachments/assets/44461b7c-44b3-418a-9415-e603be65bc66)
![grafik](https://github.com/user-attachments/assets/214ad550-bb60-413b-8727-c856f95037e4)
![grafik](https://github.com/user-attachments/assets/cddca486-75b4-4528-9e89-9f1b6343c5a8)
![grafik](https://github.com/user-attachments/assets/378e97e9-01b4-40bc-a439-acb53323a0e4)
![grafik](https://github.com/user-attachments/assets/090ea66e-dffe-467f-81c6-126798e42eaf)
![grafik](https://github.com/user-attachments/assets/0dca59c7-37fa-4576-beac-865e4d1f7509)

Thank you!

**Comment by IwonaZwierzynska** [comment] 2024-08-29 10:40
Thank you very much for your response :-)!

**Comment by pwang347** [comment] 2024-08-29 19:38
@NiKoenig seems like you are running into the same issue here: https://github.com/microsoft/vscode-data-wrangler/issues/270 (also see https://github.com/microsoft/vscode-jupyter/issues/15969)

It seems like the Jupyter kernel API is somehow not allowing us to access the kernel. Do you recall accepting/rejecting a popup window asking if Data Wrangler should be allowed access to the kernel?

**Comment by NiKoenig** [comment] 2024-09-02 06:39
Hi @pwang347 
this is exactly the problem I was having, thank you for pointing out this issue to me! :) I didn't get any popup window asking if Data Wrangler should be allowed access to the kernel. Is there a way to grant access now, e.g., in the settings? If not, I will just follow the discussion on the Jupyter side and hope that they find a solution there.

**Comment by pwang347** [comment] 2024-10-30 18:10
Hi @theice123, does this issue reproduce on a new Python file like the following?
```python
li = [1,2,3]
print(li) # <- breakpoint here and launch `li` from debugger
```

If the above does **not** work, could you also check the following:
* Does using a different Python env (if you have one) resolve the issue?
* Does the same code in a Jupyter notebook (IPYNB) file work for you?

Thanks!
