### ISSUE TITLE
Refreshing the Visualization in Data Wrangler in VS Code

### ISSUE THREAD

**Issue by Morais-Vilaca** [microsoft/vscode-data-wrangler#258] opened 2024-08-15 11:11 UTC
Type: <b>Feature Request</b>

When working with data in the Data Wrangler tool within Visual Studio Code, it's common to want to refresh or update the visualization after making changes or performing operations. One straightforward way to ensure that the visualization reflects your changes is to close and reopen the DataFrame in Data Wrangler. However, this can be somewhat cumbersome if you need to do it frequently.

Currently, there isn't a dedicated "Refresh" button in Data Wrangler that allows you to instantly update the visualization in an easier way.

Extension version: 1.6.0
VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by kycutler** [comment] 2024-08-15 21:20
Hi @Morais-Vilaca, thanks for opening this issue!

I'd like to understand your scenario better. Are you making changes to the data from within Data Wrangler, or externally from a notebook / interactive window / debugger?

Visualizations in Data Wrangler should always reflect the data displayed in the grid. If this is not the case (the grid is updating, but visualizations are not), can you please share some steps to reproduce the issue, such as a dataset and the operations you are performing within Data Wrangler?

Alternatively, it sounds like you might be making changes to the data from outside of Data Wrangler, and looking for both the data and visualizations within Data Wrangler to update. We do support manual refreshing in "Viewing" mode. Make sure you have selected "Viewing" in the top right:
![image](https://github.com/user-attachments/assets/34e93f4c-68e9-4790-95fe-79fc9eab86e5)

And then there should be a "Refresh data" button in the toolbar:
![image](https://github.com/user-attachments/assets/a97dd9f5-c90d-483e-9a06-429e45d193b6)

Unfortunately we don't currently support this in Editing mode due to challenges related to editing past steps (see #62).

Hope this helps!

**Comment by edward-b-1** [comment] 2024-09-02 15:21
If my interpretation is correct, OP is asking for a refresh button which reloads data from disk after it has been changed on disk.

For example, one may have a cell in a notebook or some other python script which creates some data file on disk.

That data file may be opened with the data wrangler, and then the file on disk may be changed.

I don't think the data wrangler will show the updated changes without closing and reopening it.

**Comment by kycutler** [comment] 2024-10-03 17:32
Closing this issue for now due to inactivity. Feel free to re-open if the solution above isn't what you're looking for.

**Closed by kycutler** 2024-10-03 17:32 UTC
Labels: info needed

**Comment by stefanopagliari** [comment] 2025-01-10 11:35
I am also facing the same issue.  A refresh button which reloads data from the environment after it has been changed from my code. Closing and reopening is currently the only option I could find
