### ISSUE TITLE
Inconsistent behaviour of "Launch Data Wrangler" button with Jupyter

### ISSUE THREAD

**Issue by ZupoLlask** [microsoft/vscode-data-wrangler#80] opened 2023-07-29 11:10 UTC
`Launch Data Wrangler` button is only visible the first time a DataFrame is displayed in a Jupyter cell.

## Environment data

-   VS Code version: 1.80.2
-   Data Wrangler Extension version (available under the Extensions sidebar): 0.15.1
-   Jupyter Extension version (available under the Extensions sidebar): 2023.6.1101941928
-   Python Extension version (available under the Extensions sidebar): 2023.12.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Pandas version: 2.0.3
-   Python and/or Anaconda version: 3.10.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

`Launch Data Wrangler` button must be visible every time a DataFrame is displayed.

## Actual behaviour

`Launch Data Wrangler` button is only visible the first time a DataFrame is displayed.

## Steps to reproduce:

1. Run the following Python code in a Jupyter cell: `import pandas as pd; df = pd.DataFrame(['a', 'b', 'c'], columns=['A']); df`
2. Notice `Launch Data Wrangler` button is visible
3. Reexecute the same cell 
4. Notice `Launch Data Wrangler` button is now not visible

**Comment by pwang347** [comment] 2023-08-01 23:37
Hi @ZupoLlask, thanks for reporting this issue! I've confirmed that there seems to be a timing issue from the VS Code notebook output renderer (specifically, the output ID seems to be incorrect as long as the code runs fast enough). Interestingly, if you run the following code instead it should work consistently:

```
import pandas as pd; df = pd.DataFrame(['a', 'b', 'c'], columns=['A']); import time; time.sleep(0.1); df
```

I'll work with the VS Code team to get this fixed and keep the thread updated.

Thanks for trying Data Wrangler!

**Comment by pwang347** [comment] 2023-08-02 20:41
I've opened an issue here: https://github.com/microsoft/vscode/issues/189488

**Comment by ZupoLlask** [comment] 2023-08-02 21:38
Thank you! 🙂

**Comment by gal-checksum** [comment] 2023-08-04 23:16
Is there a "hack" to go around it until the issue gets fixed?

Everything worked fine a few days ago, but now I'm not able to use Data Wrangler. 

Great extension!

**Comment by pwang347** [comment] 2023-08-05 00:29
Hi @gal-checksum! If you don't mind downgrading the Jupyter extension, I've found that `v2023.4.1011241018` is a working version. Alternatively, you could add `print()` on the first line of the cell and it should also make it appear consistently.

**Comment by gal-checksum** [comment] 2023-08-05 07:07
Even after downgrading (and reloading) and/or adding a `print` at the beginning of the cell, I still don't see the "Launch Data Wrangler" button consistently.

Some cells I do and others I don't. Maybe I'm experiencing a different bug?

**Comment by gal064** [comment] 2023-08-07 17:51
adding `print()` works actually. My problem was that I had a commented code after the printing the df.

So this works
```
print()
df
```

But this doesn't show the button
```
print()
df
# some comment
```

**Comment by pwang347** [comment] 2023-08-07 18:34
> adding `print()` works actually. My problem was that I had a commented code after the printing the df.
> 
> So this works
> 
> ```
> print()
> df
> ```
> 
> But this doesn't show the button
> 
> ```
> print()
> df
> # some comment
> ```

Ah yes, this is expected at the moment. For the initial release we've been extra cautious about the cases where we show the button and so the required code format is quite rigid. That being said, we have an item in our backlog to investigate expanding the launch conditions, so do stay tuned for future updates!

Assuming that @gal-checksum is your other account, did you by any chance have the comment there when you tried after downgrading? It would be helpful to know if downgrading is a confirmed fix or if it just makes it less flaky in some cases (if not, it would be awesome if you could provide an example snippet to reproduce the issue).

Also note that for this issue it is about a button not being displayed after re-execution, but it should at least be shown on the first cell run.

Thanks!

**Comment by gal064** [comment] 2023-08-07 18:40
Yep it's my other (corp) account.

Confirming that once I removed the comment, both methods worked in my case. 

This is a great tool! It might be worth documenting the constraints in the readme. I don't think the rigid requirements is a big deal, the problem for me was not knowing these requirements exists

**Comment by pwang347** [comment] 2023-08-07 18:54
> Yep it's my other (corp) account.
> 
> Confirming that once I removed the comment, both methods worked in my case.
> 
> This is a great tool! It might be worth documenting the constraints in the readme. I don't think the rigid requirements is a big issue, the problem for me was not knowing these requirements exists, so I didn't understand why the button doesn't appear

Awesome, thanks a lot for confirming and I'm glad that you're enjoying the tool! :)
Will update the README to include a note for that. Cheers!

**Comment by pwang347** [comment] 2023-08-30 22:31
Thanks for the patience folks, the bug has been fixed and should be resolved in next week's pre-release. Cheers!

**Closed by pwang347** 2023-08-30 22:31 UTC
Labels: bug
