### ISSUE TITLE
Unnecessary [DW] appears in Data Wrangler editor tabs

### ISSUE THREAD

**Issue by DavidP2Z** [microsoft/vscode-data-wrangler#264] opened 2024-08-21 10:50 UTC
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

In any Data Wrangler editor tab we see a '[DW]' appended to the tile. I assume this is to indicate the editor is a Data Wrangler - this is unnecessary as it just adds clutter; it's already very clear what the editor is, and no other VS Code editor does this to my knowledge.  This happens whether we enter from a Notebook or from an Explorer file.

## Steps to reproduce:

1. Enter the Data Wrangler from a notebook or Explorer file.

2. The text `[DW]` is appended to the title in the editor tab.

# Diagnostic data

-   Jupyter extension version: 2024.7.0
-   Python extension version: 2024.12.3
-   .NET Install Tool for Extension Authors extension version: 2.1.1
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.2",
    "pyarrow": "17.0.0"
  },
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": []
}
```

-   Entrypoint: Command
-   Active mode: dataWrangler

Extension version: 1.6.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pwang347** [comment] 2024-08-22 18:27
Hi @DavidP2Z, thanks for the feedback! The reason for this is mostly technical, given that we don't have ability to customize the editor icon (see https://github.com/microsoft/vscode/issues/105028). So the [DW] suffix is a workaround for us to identify when we can show an icon for now 😅 we do plan to remove it once it's no longer needed.

Will close this with as designed for now, but please feel free to let us know if you have any other suggestions. Thanks!

**Closed by pwang347** 2024-08-22 18:27 UTC
