### ISSUE TITLE
Data wrangler gives an error "Extension host terminated unexpectedly, restarting..."

### ISSUE THREAD

**Issue by Gravity-DWH** [microsoft/vscode-data-wrangler#187] opened 2024-05-22 12:28 UTC
I am getting some kind of error when trying to view data of pandas data frame  in Jupyter. The error is "Extension host terminated unexpectedly, restarting..."
I have tried switching to pre release versions on DataWrangler as well as on jupyter.
## Environment data

-   VS Code version: Version: 1.89.1 (user setup)
                                Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
                                Date: 2024-05-07T05:13:33.891Z
                                Electron: 28.2.8
                                ElectronBuildId: 27744544
                                Chromium: 120.0.6099.291
                                Node.js: 18.18.2
                                V8: 12.0.267.19-electron.0
                                OS: Windows_NT x64 10.0.22631

-   Data Wrangler Extension version (available under the Extensions sidebar): v1.0.2
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.0
-   Python Extension version (available under the Extensions sidebar): v2024.6.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Pandas version: 2.2.0
-   Python and/or Anaconda version: 3.11.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Expected behaviour

Showing data frame

## Actual behaviour

Not showing any data and restarting python kernal

## Steps to reproduce:

just created and data frame and opened it using Datawrangler

Jupyter shows all the variables at the time, when i try to open the df in Datawrangler getting the message "Extension host terminated unexpectedly, restarting..."

**Comment by Gravity-DWH** [comment] 2024-05-23 05:29
On first run
![image](https://github.com/microsoft/vscode-data-wrangler/assets/165262712/123a02d8-24d1-49b7-bc5e-79eca3fc1dc5)


Second run
![image](https://github.com/microsoft/vscode-data-wrangler/assets/165262712/2ab6795d-1260-444f-9b4e-0d2a5f07ffd9)

**Comment by Gravity-DWH** [comment] 2024-05-27 12:08
please let me know if you need more information.
Thanks

**Comment by kycutler** [comment] 2024-05-28 16:27
Thank you for sharing the screenshots, and for following up 🙂 is there any more error information in the "Extension Host" logs in the Output view? Also, in regards to the first screenshot, it looks like it succeeded after a restart -- did Data Wrangler open successfully here?

A couple more things to try:
- Disable all extensions other than Data Wrangler, Jupyter, and Python, to eliminate the possibility that it is caused by another extension.
- Try opening Data Wrangler from a CSV file (right click a `.csv` file -> Open in Data Wrangler) to eliminate the possibility that it is an issue with notebooks.

**Comment by Gravity-DWH** [comment] 2024-05-29 05:16
data wrangler did not open successfully as all the variables were lost during the restart. and during the next run, the same happens again.

![image](https://github.com/microsoft/vscode-data-wrangler/assets/165262712/51af1e4d-754d-4a48-838d-08904cb8a738)


- I have tried disabling all the extensions other than the specified extensions. problem still exists

- I am able to open .csv file in data wrangler

**Comment by kycutler** [comment] 2024-05-29 16:14
Thank you for the information! It's very interesting that you can still open a CSV file.

In the Data Wrangler settings, can you verify whether the "Use Jupyter Proposed API" setting is enabled? And whether the problem persists if you toggle it?

![image](https://github.com/microsoft/vscode-data-wrangler/assets/67761731/5bf026df-e047-400e-8214-148e078c4c0b)

**Comment by Gravity-DWH** [comment] 2024-05-30 10:33
It is working now. I just went and ran the program and opened a data frame. Datawrangler showed the Dataframe data, no other 
I did not do anything in the settings.
 wired , But I am Happy

**Comment by kycutler** [comment] 2024-06-07 17:57
Glad to hear the problem is resolved. Closing this issue, but feel free to re-open if it comes back. Thanks!

**Closed by kycutler** 2024-06-07 17:57 UTC
Labels: bug
