### ISSUE TITLE
Failed to update data frame: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by CommanderPho** [microsoft/vscode-data-wrangler#118] opened 2023-12-14 21:41 UTC
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2023.10.1100000000
-   Python extension version: 2023.22.1
-   .NET Install Tool for Extension Authors extension version: 2.0.0
-   Python package dependencies:

```json
{
  "satisfied": {
    "pandas": {
      "installedVersion": "1.5.3",
      "requiredVersion": "0.25.2"
    }
  },
  "unsatisfied": {}
}
```

Extension version: 0.22.2
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.6.4-100.fc38.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz (16 x 4500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|62.49GB (35.71GB free)|
|Process Argv|--user-data-dir=/home/halechr/Library/VSCode/green/user --extensions-dir=/home/halechr/Library/VSCode/green/extensions --crash-reporter-id 1a33de6a-c29f-4476-837b-4d5dd418e241|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260

```

</details>

**Comment by pwang347** [comment] 2023-12-19 23:48
Hi @CommanderPho, thanks for opening this issue. It would be helpful if you could provide a small example dataset to help us reproduce and diagnose the problem.

**Comment by brucosper** [comment] 2024-02-16 16:23
Having the same problem, seems to be an issue with nested lists. I can reproduce with this in R:

```
library(arrow)
library(tidyverse)

tibble(
  id = seq_len(2),
  nested_col = list(
    tibble(
      ids = rep(list(1,2,3), 10),
      ids2 = rep(list(2,3,4), 10)
    ),
    tibble(
      ids = rep(list(1,2,3), 10),
      ids2 = rep(list(2,3,4), 10)
    )
  )
) %>%
write_parquet("test.parquet")
```

**Comment by pwang347** [comment] 2024-02-21 20:05
Hi @brucosper, I can confirm that it repros. I'll investigate a fix for this and update the thread. Thank you!

**Comment by pwang347** [comment] 2024-02-28 18:18
Hi @CommanderPho @brucosper, just wanted to provide an update that the issue has been identified and fixed!
You should see the fix available in the next pre-release version of Data Wrangler that will come out in the next few days.

Thank you very much for reporting the issue and for trying Data Wrangler!

**Closed by pwang347** 2024-02-28 18:18 UTC
Labels: bug
