### ISSUE TITLE
"Launch Data Wrangler" button never appears in Interactive Window

### ISSUE THREAD

**Issue by dreadedhamish** [microsoft/vscode-data-wrangler#88] opened 2023-08-16 00:24 UTC
## Environment data

-   VS Code version:1.81.1
-   Data Wrangler Extension version: 0.14.0 and 0.15.3
-   Jupyter Extension version: v2023.7.1002162226
-   Python Extension version: v2023.14.0
-   OS : Manjaro (up to date)
-   Pandas version: 2.0.3
-   Python : 3.11.3
-   Type of virtual environment used : venv
-   Poetry 1.5.1

## Expected behaviour

"Launch Data Wrangler" button appears in interactive window after entering a command like "df"

## Actual behaviour

"Launch Data Wrangler" button never appears (not even the first time).

This might be related to https://github.com/microsoft/vscode-data-wrangler/issues/80 but in my case I don't get the button even the first time, and the workaround of using:
```
print()
df
```
doesn't overcome the issue.

I am using Poetry to manage my venv if that makes a difference.
I can successfully open a CSV from the file browser, and Data Wrangler is using the kernel from my venv.
I can't however trigger Data Wrangler from the Interactive Window.

**Comment by pwang347** [comment] 2023-08-16 17:53
Hi @dreadedhamish!

We currently don't support launching from Interactive Window due to API limitations (more context in https://github.com/microsoft/vscode-data-wrangler/issues/18).

Otherwise, the change on our side to enable this scenario is very straightforward; so if this is something you'd like to see, I'd strongly encourage you to go ahead and give https://github.com/microsoft/vscode-jupyter/issues/13130 an upvote!

In the meantime, using a `.ipynb` file should be possible as a workaround. I'll close this issue as a duplicate of the other one, but feel free to reopen if this doesn't address your problem. Thanks!

**Closed by pwang347** 2023-08-16 17:53 UTC

**Comment by dreadedhamish** [comment] 2023-08-17 02:01
> Hi @dreadedhamish!
> 
> We currently don't support launching from Interactive Window due to API limitations (more context in #18).
> 
> Otherwise, the change on our side to enable this scenario is very straightforward; so if this is something you'd like to see, I'd strongly encourage you to go ahead and give [microsoft/vscode-jupyter#13130](https://github.com/microsoft/vscode-jupyter/issues/13130) an upvote!
> 
> In the meantime, using a `.ipynb` file should be possible as a workaround. I'll close this issue as a duplicate of the other one, but feel free to reopen if this doesn't address your problem. Thanks!

Thanks! I've never used proper Jupyter before but I just created my first project and got Data Wrangler working within it. For now I'll keep a seperate project dedicated to manipulating data when I'm doing an initial import.
