### ISSUE TITLE
UTC +8 in jupyter notebook but UTC in Data Wrangler UI

### ISSUE THREAD

**Issue by shaunpwl** [microsoft/vscode-data-wrangler#32] opened 2023-04-12 09:41 UTC
## Environment data

-   VS Code version: 1.78.0-insider
-   Data Wrangler Extension version (available under the Extensions sidebar): 0.60
-   Jupyter Extension version (available under the Extensions sidebar): v2023.4.1001031011
-   Python Extension version (available under the Extensions sidebar): v2023.6.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Pandas version: 1.1.3
-   Python and/or Anaconda version: 2.0.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

show same timezone as jupyter notebook, i.e UTC +8

## Actual behaviour

shows UTC timezone

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. convert column in notebook to UTC +8
2. display in both notebooke and data wrangler UI and compare

**Comment by jmew** [comment] 2023-04-17 17:18
@shaunpwl Thanks for logging the issue! I can confirm that I was able to reproduce the issue.

![image](https://user-images.githubusercontent.com/15910920/232560910-ac2a5913-e914-429a-9058-10398da880c3.png)

![image](https://user-images.githubusercontent.com/15910920/232560957-fe16ae50-606e-4295-a2a1-e085b08a6266.png)

We will investigate this issue and look to see what the root cause is.

**Comment by pwang347** [comment] 2023-04-18 01:36
Hi @shaunpwl, just letting you know that the fix for this display bug has been merged and will be available in the next release (^0.7.0, available in the next day or two).

Thanks for reporting!

**Closed by pwang347** 2023-04-18 01:36 UTC
Labels: bug
