### ISSUE TITLE
No  "view in Data Wrangler" while debugging a module

### ISSUE THREAD

**Issue by ibobak** [microsoft/vscode-data-wrangler#196] opened 2024-06-02 15:21 UTC
Type: <b>Bug</b>

I am working with jupyter notebook, and I am debugging a cell,  stepped in a function which is in the module, and here is my question:
![image](https://github.com/microsoft/vscode-data-wrangler/assets/8807043/c706e1dc-1d5a-4f28-963a-6a1dd358b4f3)

So, in general, I want to have ability to view a dataframe in wrangler while debugging, but neither in context menu, nor in the watch window I can't access this function.

Extension version: 1.2.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz (88 x 1197)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|251.76GB (227.64GB free)|
|Process Argv|--crash-reporter-id 27d42247-63fb-4d9e-9cb0-87d9974843dc|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:31064718
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by pwang347** [comment] 2024-06-03 22:52
Hi @ibobak, thanks for opening this issue! This seems to be a duplicate of [https://github.com/microsoft/vscode-data-wrangler/issues/131](https://github.com/microsoft/vscode-data-wrangler/issues/49).

Could you please install [VS Code Insiders](https://code.visualstudio.com/insiders/) and try again with the latest **pre-release** version of [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)? Alternatively, if you don't mind waiting this change is expected to be available sometime this week or next when VS Code's May 2024 update is available.

Hope that helps!

**Closed by pwang347** 2024-06-03 22:52 UTC
