### ISSUE TITLE
DW fail to open while right clicking on csv file from vscode

### ISSUE THREAD

**Issue by HugoPOIDVIN** [microsoft/vscode-data-wrangler#280] opened 2024-09-10 15:41 UTC
## Environment data

-   VS Code version: 1.87.2
-   Data Wrangler Extension version (available under the Extensions sidebar): 1.8.0
-   Jupyter Extension version (available under the Extensions sidebar): 2024.2.0
-   Python Extension version (available under the Extensions sidebar): 2024.4.1
-   OS (Windows | Mac | Linux distro) and version: MacOS Sonoma 14.6.1
-   Pandas version: 2.2.2
-   Python and/or Anaconda version: Python 3.11.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv

## Expected behaviour

File should open in a new tab when clicking on a csv and then on "open with DW'

## Actual behaviour

DW window open but load infinitely

## Steps to reproduce:

Go to a project directory, right click on a csv file using sidebar and click on "open with DW"

**Comment by pwang347** [comment] 2024-09-10 18:23
Hi @HugoPOIDVIN, thank you for opening this issue! Could you please share some more information about the dataset you are trying to load? It would be great for you to share a dataset where it is not working. If you are not able to share the dataset, it would be great if you could obfuscate it or share a smaller version of it.

Thanks!

**Comment by HugoPOIDVIN** [comment] 2024-09-11 07:40
Hi @pwang347 thank you for your answer, unfortunately, I won't be able to share the dataset i'm working on, as it contains customers informations. I won't have the time to modify it to share it to you, but here are few points : 

- I was working on the exact same dataset few weeks ago and everything was working fine
- the dataset contains 17.000 lines, +- 10 columns for a total of 3.2 MB
- I'm currently trying to open others csv from others projects using DW and i'm facing the same issue, perhaps i've a problem with the extension, would you recommend me to reinstall it ?

**Comment by HugoPOIDVIN** [comment] 2024-09-11 12:31
Just switched back to 1.6.0 version and it works, seems like there's an issue with latest version ?

**Comment by pwang347** [comment] 2024-09-11 18:56
Hi @HugoPOIDVIN, thanks for the update. Seems like this is a dupe of https://github.com/microsoft/vscode-data-wrangler/issues/282 - we've merged a fix into 1.8.1 which should address it, but please let me know if the issue is still occurring for you!

**Closed by pwang347** 2024-09-11 18:56 UTC
Labels: info needed
