### ISSUE TITLE
DataWarangler

### ISSUE THREAD

**Issue by chrisschneble** [microsoft/vscode-data-wrangler#127] opened 2024-01-23 12:26 UTC
Type: <b>Bug</b>

# Behaviour

Failed to update data frame: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()Failed to update data frame: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()Failed to update data frame: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()Failed to update data frame: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()Failed to update data frame: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2023.11.1100101639
-   Python extension version: 2023.22.1
-   .NET Install Tool for Extension Authors extension version: 2.0.0
-   Python package dependencies:

```json
{
  "satisfied": {
    "pandas": {
      "installedVersion": "2.1.3",
      "requiredVersion": "0.25.2"
    }
  },
  "unsatisfied": {}
}
```

Extension version: 0.22.3
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1370P (20 x 2189)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (17.50GB free)|
|Process Argv|--crash-reporter-id 258a4be1-91d0-4107-a439-66ea08dced0c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30933248
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by pwang347** [comment] 2024-01-24 02:11
Hi @chrisschneble, thanks for reporting this issue! Could you please share a small sample file or code that causes the error to reproduce?

**Comment by chrisschneble** [comment] 2024-01-24 14:12
Dear Paul it occours after reading a parquet-file. Here is the code that I use to read the parquet file.

import pyarrow.parquet as pq
test=pq.read_table("data_test/MyFile.parquet").to_pandas()

**Comment by pwang347** [comment] 2024-01-25 18:16
@chrisschneble If possible, could you please also attach the parquet file as well? Maybe just a row or two to reproduce the issue would be great (perhaps you may also want to obfuscate some of the data if it is sensitive).

Thank you!

**Comment by pwang347** [comment] 2024-02-21 20:06
Closing as a dupe of https://github.com/microsoft/vscode-data-wrangler/issues/118 as that one has a repro. Thanks!

**Closed by pwang347** 2024-02-21 20:06 UTC
Labels: info needed
